spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdata?verifyServerCertificate=false&useSSL=false
    username: root
    password: SaAm_4106
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 1000